SAM_DATASET_PATH = '/home/lujiahao/dataset/sa_000000/'
PROJECT_PATH='/home/lujiahao/anything-unsegmentable/'
SAM_B_PATH = '/home/lujiahao/anything-unsegmentable/checkpoints/sam_vit_b_01ec64.pth'
SAM_L_PATH = '/home/lujiahao/anything-unsegmentable/checkpoints/sam_vit_l_0b3195.pth'
SAM_H_PATH = '/home/lujiahao/anything-unsegmentable/checkpoints/sam_vit_h_4b8939.pth'
FASTSAM_PATH = '/home/lujiahao/anything-unsegmentable/checkpoints/FastSAM-x.pt'